Add version verification to workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -2,15 +2,31 @@ name: Publish package
 
 on:
   release:
-    types: [published] # run when a new release is published
+    types: [created, published] # run when a new release is published
     
+env:
+  cleanVersion:  ${{github.event.tag_name}}
+  name: ${{github.event.repository.name}} # Edit this if the package name differs from the repo name
+
 jobs:
-  publish:
+  verify:
     runs-on: ubuntu-latest
     steps:
-      - name: Get repo name # This can be deleted when manually setting the package name
+      - uses: actions/checkout@v3
+      - name: Check that version matches
         run: |
-          "echo name=$(echo ${{ github.repository }} | sed s:*/::) >> GITHUB_ENV"
+          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
+            echo "::debug::${{env.cleanVersion}}"
+            echo "::debug::$(cat $(find ./ -name mod.json ))"
+            echo "::error::Version in mod.json does not match tag version"
+            exit 1
+          fi
+  publish:
+    if: ${{github.event.action}} == "published" # only run on publish events
+    runs-on: ubuntu-latest
+    needs: verify
+    steps:
+      - uses: actions/checkout@v3
       - name: Upload Thunderstore Package
         uses: GreenTF/upload-thunderstore-package@v1
         with:
@@ -21,7 +37,7 @@ jobs:
           # Name of the package
           name: ${{ env.name }} # This can be modified if the package name differs from the repo name
           # Package version to publish
-          version: ${{ github.ref_name }} # This is the tag that was created in the release
+          version: ${{ env.cleanVersion }} # This is the tag that was created in the release but without the leading 'v'
           # Description of the mod
           description: Example mod description # <----- UPDATE THIS
           # Thunderstore API token
